[rospy.client][INFO] 2022-02-14 13:22:22,846: init_node, name[/sensor/tactile_pressure], pid[1244]
[xmlrpc][INFO] 2022-02-14 13:22:22,847: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-02-14 13:22:22,847: Started XML-RPC server [http://FM00351-u:40759/]
[rospy.init][INFO] 2022-02-14 13:22:22,847: ROS Slave URI: [http://FM00351-u:40759/]
[rospy.impl.masterslave][INFO] 2022-02-14 13:22:22,847: _ready: http://FM00351-u:40759/
[xmlrpc][INFO] 2022-02-14 13:22:22,847: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2022-02-14 13:22:22,848: Registering with master node http://localhost:11311
[rospy.init][INFO] 2022-02-14 13:22:22,947: registered with master
[rospy.rosout][INFO] 2022-02-14 13:22:22,948: initializing /rosout core topic
[rospy.rosout][INFO] 2022-02-14 13:22:22,953: connected to core topic /rosout
[rospy.simtime][INFO] 2022-02-14 13:22:22,954: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2022-02-14 13:22:22,959: ROS Serial Python Node
[rosout][INFO] 2022-02-14 13:22:22,961: Connecting to /dev/ttyACM0 at 57600 baud
[rosout][ERROR] 2022-02-14 13:22:22,963: Error opening serial: [Errno 21] could not open port /dev/ttyACM0: [Errno 21] Is a directory: '/dev/ttyACM0'
[rospy.internal][INFO] 2022-02-14 13:22:23,269: topic[/rosout] adding connection to [/rosout], count 0
[rosout][ERROR] 2022-02-14 13:22:25,964: Error opening serial: [Errno 21] could not open port /dev/ttyACM0: [Errno 21] Is a directory: '/dev/ttyACM0'
[rosout][ERROR] 2022-02-14 13:22:28,970: Error opening serial: [Errno 21] could not open port /dev/ttyACM0: [Errno 21] Is a directory: '/dev/ttyACM0'
[rosout][ERROR] 2022-02-14 13:22:31,977: Error opening serial: [Errno 21] could not open port /dev/ttyACM0: [Errno 21] Is a directory: '/dev/ttyACM0'
[rospy.core][INFO] 2022-02-14 13:22:32,135: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-02-14 13:22:32,139: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2022-02-14 13:22:32,139: signal-2
[rospy.core][INFO] 2022-02-14 13:22:32,272: signal_shutdown [atexit]
